inherit_from: .rubocop_todo.yml


AllCops:
  Exclude:
      - 'db/schema.rb'
      - 'node_modules/**/*'


Rails:
  Enabled: true


# Cop supports --auto-correct.
# Configuration parameters: EnforcedHashRocketStyle, EnforcedColonStyle, EnforcedLastArgumentHashStyle.
# SupportedHashRocketStyles: key, separator, table
# SupportedColonStyles: key, separator, table
# SupportedLastArgumentHashStyles: always_inspect, always_ignore, ignore_implicit, ignore_explicit
Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table


# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: empty_lines, no_empty_lines
Layout/EmptyLinesAroundBlockBody:
  Enabled: false


# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: empty_lines, empty_lines_except_namespace, empty_lines_special, no_empty_lines, beginning_only, ending_only
Layout/EmptyLinesAroundClassBody:
  Enabled: false


# Cop supports --auto-correct.
Layout/EmptyLinesAroundMethodBody:
  Enabled: false


# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: empty_lines, empty_lines_except_namespace, empty_lines_special, no_empty_lines
Layout/EmptyLinesAroundModuleBody:
  Enabled: false


Lint/AmbiguousRegexpLiteral:
  Enabled: false


Metrics/AbcSize:
  Max: 23


# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 33


# Configuration parameters: CountComments, ExcludedMethods.
Metrics/MethodLength:
  Max: 27


# Configuration parameters: AllowedChars.
Style/AsciiComments:
  Enabled: false


# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, EnforcedStyle.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Enabled: false


Style/Documentation:
  Enabled: false


Style/MixinUsage:
  Exclude:
    - 'bin/**'


# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
# IgnoredMethods: respond_to, define_method
Style/SymbolProc:
  Enabled: false


# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Enabled: false
